name: Android CI

on:
   workflow_dispatch :
   schedule :
    - cron: '0 0 * * *'
   push:
      branches: [ main ]
   pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
  #  Default gardle settings are sufficient. Can be used for custom gradle setting
  #  - name: Copy CI gradle.properties
  #   run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
      
    - name: Build with Gradle
      run: ./gradlew assembleRelease
      
    - name: Upload apk
      uses: actions/upload-artifact@v4
      with:
       name: relesse-apk
       path: app/build/outputs/apk/release/app-release.apk
#  Used for uploading generated apk for future use
